class BadRequestError(Exception): ...
class RequiredError(Exception): ...
class ClientError(Exception): ...
class UnauthorizedError(Exception): ...
class ForbiddenError(Exception): ...
class TooManyRequestsError(Exception): ...
class RateLimitBanError(Exception): ...
class ServerError(Exception): ...
class NetworkError(Exception): ...

__all__ = [
    "BadRequestError",
    "RequiredError",
    "ClientError",
    "UnauthorizedError",
    "ForbiddenError",
    "TooManyRequestsError",
    "RateLimitBanError",
    "ServerError",
    "NetworkError",
]
