from typing import Any

DERIVATIVES_TRADING_USDS_FUTURES_REST_API_PROD_URL: str
DERIVATIVES_TRADING_USDS_FUTURES_REST_API_TESTNET_URL: str

class ConfigurationRestAPI:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        base_path: str,
        timeout: int,
    ) -> None: ...

class _RestAPI:
    def exchange_information(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_current_position_mode(self, *args: Any, **kwargs: Any) -> Any: ...
    def change_position_mode(self, *args: Any, **kwargs: Any) -> Any: ...
    def position_information_v3(self, *args: Any, **kwargs: Any) -> Any: ...
    def account_information_v3(self, *args: Any, **kwargs: Any) -> Any: ...
    def futures_account_balance_v3(self, *args: Any, **kwargs: Any) -> Any: ...
    def new_order(self, *args: Any, **kwargs: Any) -> Any: ...
    def query_order(self, *args: Any, **kwargs: Any) -> Any: ...
    def cancel_order(self, *args: Any, **kwargs: Any) -> Any: ...
    def open_orders(self, *args: Any, **kwargs: Any) -> Any: ...
    def current_open_orders(self, *args: Any, **kwargs: Any) -> Any: ...
    def change_initial_leverage(self, *args: Any, **kwargs: Any) -> Any: ...

class DerivativesTradingUsdsFutures:
    def __init__(self, config_rest_api: ConfigurationRestAPI) -> None: ...
    @property
    def rest_api(self) -> _RestAPI: ...

__all__ = [
    "DERIVATIVES_TRADING_USDS_FUTURES_REST_API_PROD_URL",
    "DERIVATIVES_TRADING_USDS_FUTURES_REST_API_TESTNET_URL",
    "ConfigurationRestAPI",
    "DerivativesTradingUsdsFutures",
]
